In [1]:
import numpy as np

Create a 2D array

In [2]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print("Original array:\n", arr)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


Find shape, number of dimensions, and size

In [3]:
print("Shape:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Size:", arr.size)

Shape: (3, 3)
Number of dimensions: 2
Size: 9


Extract second row

In [4]:
print("Second row:", arr[1])

Second row: [4 5 6]


Extract third column

In [5]:
print("Third column:", arr[:, 2])

Third column: [3 6 9]


Bottom-right 2x2 sub-array

In [6]:
print("Bottom-right 2x2 sub-array:\n", arr[1:, 1:])

Bottom-right 2x2 sub-array:
 [[5 6]
 [8 9]]


Change datatype to float64

In [7]:
arr_float = arr.astype(np.float64)
print("Array as float64:\n", arr_float)

Array as float64:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


Add 5 to every element

In [8]:
added = arr_float + 5
print("After adding 5:\n", added)

After adding 5:
 [[ 6.  7.  8.]
 [ 9. 10. 11.]
 [12. 13. 14.]]


Multiply array with itself (element-wise)

In [9]:
multiplied = arr_float * arr_float
print("Element-wise multiplication:\n", multiplied)

Element-wise multiplication:
 [[ 1.  4.  9.]
 [16. 25. 36.]
 [49. 64. 81.]]


Sum row-wise

In [10]:
print("Row-wise sum:", arr.sum(axis=1))

Row-wise sum: [ 6 15 24]


Sum column-wise

In [11]:
print("Column-wise sum:", arr.sum(axis=0))

Column-wise sum: [12 15 18]
