In [ ]:
import numpy as np
data = np.random.randn(7, 4)

In [3]:
data

array([[-0.95892265,  0.63692663, -0.24727554, -0.69821251],
       [-1.40442525,  0.36236229,  1.68032887, -1.52094646],
       [-0.4825161 ,  0.5596346 , -0.70974527,  1.55428309],
       [-0.83632171, -1.15205347, -0.08894251, -1.29645457],
       [-0.1383692 , -1.29298548, -0.67701677, -0.76627661],
       [-0.56659948, -0.77635217,  0.17081048,  1.84624759],
       [-0.53889301, -0.33917067,  1.72651462, -1.64879171]])

In [4]:
data[data<0] = 0
data

array([[0.        , 0.63692663, 0.        , 0.        ],
       [0.        , 0.36236229, 1.68032887, 0.        ],
       [0.        , 0.5596346 , 0.        , 1.55428309],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.17081048, 1.84624759],
       [0.        , 0.        , 1.72651462, 0.        ]])

In [5]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [6]:
names[names=='Joe'] = 7
names

array(['Bob', '7', 'Will', 'Bob', 'Will', '7', '7'], dtype='<U4')

In [11]:
arr = np.empty([8,4])
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
for i in range(8):
    arr[i]=i
    
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [ ]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [17]:
arr[[4,-3,0,6]]

array([[4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [20]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [23]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [25]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [26]:
arr.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [28]:
arr2 = np.arange(16).reshape((2,2,4))
arr2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [38]:
arr2[1,1,1]

13

In [29]:
arr2.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [40]:
arr2.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])