SECTION A

In [12]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70])
arr

array([10, 20, 30, 40, 50, 60, 70])

In [13]:
arr[[0,2,4,6]]

array([10, 30, 50, 70])

In [14]:
arr[[1,4,6]]

array([20, 50, 70])

In [15]:
arr[::-1]

array([70, 60, 50, 40, 30, 20, 10])

In [16]:
arr[[1,3,5]] = 0
arr

array([10,  0, 30,  0, 50,  0, 70])

In [17]:
arr[arr>30]

array([50, 70])

SECTION B

In [22]:
arr = np.array([12,45,67,23,89,10,55])

In [23]:
arr[arr>50]

array([67, 89, 55])

In [ ]:
arr[arr<20] = -1

In [24]:
count = np.sum((arr >= 20) & (arr <= 60))
count

3

In [25]:
arr[arr % 2 == 0]

array([12, 10])

In [26]:
arr[arr > 40] ** 2

array([2025, 4489, 7921, 3025])

SECTION C

In [27]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [28]:
arr[[0, 1, 2], [0, 1, 2]]

array([10, 50, 90])

In [29]:
arr[[0, 1, 2], [2, 1, 0]]

array([30, 50, 70])

In [30]:
arr[[0, 2]]

array([[10, 20, 30],
       [70, 80, 90]])

In [31]:
arr[:, [1, 2]]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [32]:
arr[arr < 40] = 0
arr

array([[ 0,  0,  0],
       [40, 50, 60],
       [70, 80, 90]])

SECTION D

In [ ]:
arr = np.arange(24).reshape(2, 3, 4)
arr.shape

(2, 3, 4)

In [ ]:
t1 = arr.transpose(1, 0, 2)
t1
t1.shape

(3, 2, 4)

In [38]:
t2 = arr.transpose(2, 1, 0)
t2
t2.shape

(4, 3, 2)

In [39]:
swapped = arr.swapaxes(0, 1)
swapped.shape

(3, 2, 4)