In [3]:
import numpy as np

a. Compute the mean, standard deviation, and variance of a two dimensional random integer array along the second axis. 

In [4]:
arr2d = np.random.randint(1, 100, (4, 5))
print("2D Array:\n", arr2d)
print("Mean:", np.mean(arr2d, axis=1))
print("Standard Deviation:", np.std(arr2d, axis=1))
print("Variance:", np.var(arr2d, axis=1))

2D Array:
 [[83  9 85 70 49]
 [84 25 84  8 44]
 [74  9 12  7 18]
 [54 61  5  9 59]]
Mean: [59.2 49.  24.  37.6]
Standard Deviation: [28.18794068 30.76361487 25.27449307 25.12050955]
Variance: [794.56 946.4  638.8  631.04]


b.  Create a 2-dimensional array of size m x n integer elements, also print the shape, type and data type of the array and then reshape it into an n x m array, where n and m are user inputs given at the run time.

In [10]:
m = int(input("Enter m: "))
n = int(input("Enter n: "))

arr = np.random.randint(1, 50, (m, n))
print("\nOriginal Array:\n", arr)
print("Shape:", arr.shape)
print("Type:", type(arr))
print("Data Type:", arr.dtype)

reshaped_arr = arr.reshape(n, m)
print("Reshaped Array:\n", reshaped_arr)


Original Array:
 [[36 16 13 11 37]
 [ 2 15 28 39 19]
 [41 29 14 37  2]
 [28 41  2 24 27]]
Shape: (4, 5)
Type: <class 'numpy.ndarray'>
Data Type: int64
Reshaped Array:
 [[36 16 13 11]
 [37  2 15 28]
 [39 19 41 29]
 [14 37  2 28]
 [41  2 24 27]]


c. Test whether the elements of a given 1D array are zero, non-zero and NaN. Record the indices of these elements in three separate arrays. 

In [7]:
arr1d = np.array([0, 4, np.nan, 7, 0, 9, np.nan])
print("\n1D Array:", arr1d)

zero_indices = np.where(arr1d == 0)
nonzero_indices = np.where(arr1d != 0)
nan_indices = np.where(np.isnan(arr1d))

print("Zero indices:", zero_indices)
print("Non-zero indices:", nonzero_indices)
print("NaN indices:", nan_indices)


1D Array: [ 0.  4. nan  7.  0.  9. nan]
Zero indices: (array([0, 4]),)
Non-zero indices: (array([1, 2, 3, 5, 6]),)
NaN indices: (array([2, 6]),)


d. Create three random arrays of the same size: Array1, Array2 and Array3. Subtract Array 2 from Array3 and store in Array4. Create another array Array5 having two times the values in Array1. Find Co variance and Correlation of Array1 with Array4 and Array5 respectively. 

In [11]:
Array1 = np.random.randint(1, 50, (10))
Array2 = np.random.randint(1, 50, (10))
Array3 = np.random.randint(1, 50, (10))

Array4 = Array3 - Array2
Array5 = 2 * Array1

print("\nArray1:", Array1)
print("Array4:", Array4)
print("Array5:", Array5)

print("Covariance:\n", np.cov(Array1, Array4))
print("Correlation:\n", np.corrcoef(Array1, Array5))


Array1: [41 29 21  4 28 44 37 20 39 13]
Array4: [  4 -28  18 -20 -12   8 -10 -20  11  -9]
Array5: [82 58 42  8 56 88 74 40 78 26]
Covariance:
 [[171.15555556  89.86666667]
 [ 89.86666667 233.06666667]]
Correlation:
 [[1. 1.]
 [1. 1.]]


e. Create two random arrays of the same size 10: Array1, and Array2. Find the sum of the first half of both the arrays and product of the second half of both the arrays. 

In [9]:
Array1 = np.random.randint(1, 10, 10)
Array2 = np.random.randint(1, 10, 10)

print("\nArray1:", Array1)
print("Array2:", Array2)

print("Sum of first half:", np.sum(Array1[:5] + Array2[:5]))
print("Product of second half:", np.prod(Array1[5:] * Array2[5:]))


Array1: [9 2 8 7 5 4 2 9 1 9]
Array2: [2 8 8 7 2 3 9 5 7 3]
Sum of first half: 58
Product of second half: 1837080
